import Head from "next/head";
import { Inter } from "@next/font/google";
import MessageInputBar from "@/chat/inputBar";
import Messages from "@/chat/messages";
import useMessage from "@/reactQuery/useMessage";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
const inter = Inter({ subsets: ["latin"] });
export const getServerSideProps: GetServerSideProps<any> = async (ctx) => {
  if (ctx.resolvedUrl && ctx.locale) {
    return {
      props: {
        ...(await serverSideTranslations(ctx.locale, ["common"])),
      },
    };
  } else {
    return {
      props: {
        data: "nothing yet",
      },
    };
  }
};
export default function Home(props: any) {
  const { t } = useTranslation();
  console.log(props.data);
  const { chatHistory, sendUserMessage } = useMessage();
  return (
    <>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          width: "100vw",
          padding: "0 5px",
          position: "relative",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        {t(`common:greet`)}
        <Messages messages={chatHistory} />
        <MessageInputBar sendMessage={sendUserMessage} />
      </main>
    </>
  );
}
